/** Target Rescue — the third, separate simulation mode.
 *
 *  Mirrors backend/app/tpo/rescue.py. Nothing in here overlaps the Investigation
 *  Simulation's contracts in types/simulation.ts or General Optimization's in
 *  types/optimization.ts: the three modes share the filter dimensions, the
 *  approved economics and the KPI definitions, and no type.
 *
 *  EVERY PROJECTED FIGURE IS A BAND, never a point. An approved treatment gives
 *  an uplift RANGE (PR003 is 40–50%), and the backend refuses to collapse one to
 *  a midpoint — so `RescueBand` is the shape every modelled number arrives in.
 *
 *  A `null` IS NOT A ZERO anywhere in this file. A figure the backend could not
 *  produce arrives null with its reason beside it, and the screen renders the
 *  reason rather than a zero that would read as a measurement.
 */

/** One figure at both ends of its approved uplift band. */
export interface RescueBand {
  low: number | null
  high: number | null
  display_low: string
  display_high: string
  /** Pre-formatted "43,210 – 44,644", or the single value when the two ends
   *  coincide (the maintain rung does not move). */
  display: string
}

export type RescueStatus = 'evaluated' | 'no_data'

/** Where in the month the evaluation sits, which decides how much weight the
 *  evidence carries. */
export type RescuePhase = 'early_month' | 'checkpoint' | 'complete'

/** The brief's target bands, plus the two closed-month outcomes. */
export type TargetStatusCode = 'on_track' | 'watch' | 'at_risk' | 'achieved' | 'missed'

/** How aggressive a rung is. `maintain` is the measured remainder and carries no
 *  approved depth at all. */
export type InterventionKind = 'maintain' | 'discount' | 'clearance'

/** The channel's promotion planning cadence, from the project's own declaration
 *  (`promo_calendar.CADENCE`). MIXED is a scope holding both kinds — an
 *  all-channels selection, or two channels that plan differently. */
export type CadenceCode = 'WEEKLY' | 'MONTHLY' | 'MIXED'

/** How the checkpoint week was arrived at. `auto` follows the cadence; `week` is
 *  an explicit choice; `latest` is the month's last completed week. */
export type CheckpointType = 'auto' | 'week' | 'latest'

/** What the checkpoint control may be set to. A WEEK ORDINAL, never a day —
 *  progress in this dataset is knowable at complete-business-week boundaries and
 *  nowhere finer. */
export type CheckpointValue = number | 'auto' | 'latest'

/** One selectable dimension value, as the cascade returns it. `code` is the real
 *  data value (Channel_Id, Product_id, or the category string); `name` is the
 *  business label from the dimension table. */
export interface CascadeOption {
  code: string
  name: string
}

/** CHANNEL -> CATEGORY -> PRODUCT, strictly top-down.
 *
 *  Generated by the backend from the rows each level above admits, using the same
 *  `filters.options_for` the Insights Hub uses — so an option appears if and
 *  only if selecting it returns at least one row. The frontend never derives a
 *  reachable value of its own.
 *
 *  Each list is computed with the levels BELOW it lifted, which is what makes the
 *  hierarchy climbable: a selected product does not collapse the category list to
 *  that product's own category. */
export interface CascadeOptions {
  channels: CascadeOption[]
  /** Categories that trade in the selected channel and month. */
  categories: string[]
  /** Products that trade in the selected channel, month AND category. */
  products: CascadeOption[]
  basis: string
  hierarchy: string[]
}

export interface CadenceChannel {
  channel_id: string
  name: string
  cadence: 'WEEKLY' | 'MONTHLY'
  /** False when `promo_calendar.CADENCE` does not declare this channel, so the
   *  MONTHLY fallback is visible rather than absorbed. */
  declared: boolean
}

export interface CadenceBlock {
  code: CadenceCode
  label: string
  /** True only when EVERY channel in scope plans weekly. A mixed scope is
   *  deliberately not weekly. */
  weekly: boolean
  channels: CadenceChannel[]
  mixed: boolean
  undeclared_channels: string[]
  basis: string
  checkpoint_rule: string
}

export interface CheckpointOption {
  value: CheckpointValue
  label: string
  ordinal: number
  week_key: string | null
  days_covered?: number
  /** What choosing this option would leave for an intervention to act on. Zero
   *  means a final result and no ladder. */
  weeks_remaining: number
  note: string
}

export interface CheckpointBlock {
  checkpoint_type: CheckpointType
  checkpoint_week: number
  checkpoint_label: string
  week_key: string | null
  requested: CheckpointValue | null
  weeks_completed: number
  weeks_total: number
  weeks_remaining: number
  /** Days the completed weeks cover, from the authoritative calendar. Derived
   *  from the weeks for the run-rate — never a daily sales read. */
  days_elapsed: number
  days_in_month: number
  auto_rule: string
  options: CheckpointOption[]
  note: string
}

export interface RescueScopeBlock {
  cadence: CadenceBlock
  year: number | null
  month: number | null
  month_label: string | null
  period_label: string
  channel: string[] | null
  channel_label: string
  category: string[] | null
  category_label: string
  product: string[] | null
  /** The product's business name from dim_product, or "All products". */
  product_label: string
  /** Section 6's one-line scope, assembled on the server so the screen and the
   *  API cannot describe the same scope differently. */
  scope_summary: string
  weeks_in_month: number
  days_in_month: number
  /** Cumulative days after each business week — the only days progress can be
   *  measured at, and therefore the only positions the checkpoint may take. */
  week_boundaries: number[]
  week_keys: string[]
  week_ordinals: Record<string, number>
  elapsed_weeks: string[]
  remaining_weeks: string[]
  weeks_completed: number
  weeks_total: number
  weeks_remaining: number
  filters_applied: Record<string, unknown>
  available_years: number[]
  /** The CASCADE's categories, not the whole catalogue — a category that does not
   *  trade in this channel and month is not a choice. */
  available_categories: string[]
}

export interface RescueReferenceTarget {
  units: number | null
  units_display: string
  year: number | null
  available: boolean
  basis: string | null
  unavailable_reason: string | null
}

export interface RescueMeasured {
  month_units: number
  month_units_display: string
  units_mtd: number
  units_mtd_display: string
  elapsed_depth_pct: number | null
  elapsed_depth_display: string
  month_depth_pct: number | null
  depth_basis: string
  mtd_basis: string
}

export interface ApprovedPoint {
  discount_pct: number
  treatment: string
  /** The promotion master's own name — "15% Discount", "Buy3Get1". */
  name: string
  uplift_low: number
  uplift_high: number
  breakeven_uplift: number
  clearance: boolean
}

export interface RescueDiscountBlock {
  min_pct: number
  max_pct: number
  approved_points: ApprovedPoint[]
  note: string
}

export interface RescueBudget {
  /** Null when no ceiling was applied. */
  max_additional_trade_spend: number | null
  max_additional_trade_spend_display: string
  applied: boolean
  /** The measured mean trade spend that bounds the control. Null makes the
   *  control unavailable — the brief forbids inventing a ceiling. */
  average_trade_spend: number | null
  display_average: string
  available: boolean
  observed_years: number
  years: number[]
  basis: string
  unavailable_reason: string | null
  note: string
}

export interface RescueProgress {
  checkpoint_type: CheckpointType
  checkpoint_week: number
  checkpoint_label: string
  week_key: string | null
  weeks_completed: number
  weeks_total: number
  weeks_remaining: number
  /** Derived from the completed weeks, for the run-rate. Not a daily read. */
  days_elapsed: number
  days_in_month: number
  days_remaining: number
  boundaries: number[]
  /** Month-to-date: the sum of actual units over the COMPLETED business weeks. */
  units_mtd: number
  units_mtd_display: string
  /** The same figure under its original name, so an older client is not handed
   *  nothing. */
  units_sold: number
  units_sold_display: string
  target_units: number
  target_units_display: string
  attainment_pct: number | null
  target_attainment: number | null
  attainment_display: string
  phase: RescuePhase
  phase_note: string
  mtd_basis: string
}

export interface RescueTargetStatus {
  code: TargetStatusCode
  label: string
  /** The platform's existing status vocabulary — success | warning | danger. */
  intent: 'success' | 'warning' | 'danger'
  action: string
  final: boolean
  thresholds: { on_track_pct: number; watch_pct: number; basis: string }
}

export interface RescuePace {
  daily_pace: number | null
  daily_pace_display: string
  projected_month_end: number | null
  projected_month_end_display: string
  projected_achievement_pct: number | null
  days_remaining: number
  /** Always "Run-rate projection". Deliberately not the word "forecast". */
  label: string
  note: string
  unavailable_reason: string | null
}

export interface RescueGap {
  /** Never negative. A target already passed has no gap. */
  units: number
  units_display: string
  on_track: boolean
  label: string
  surplus_units: number | null
}

export interface RescueCurrentTreatment {
  discount_pct: number
  discount_display: string
  treatment: string | null
  name: string | null
  requested_pct: number
  /** True when the requested position was not an approved depth. */
  snapped: boolean
  measured_depth_pct: number | null
  measured_depth_display: string
  at_ceiling: boolean
  ceiling_pct: number
  /** Present only when no approved treatment is deeper than the current one. */
  no_stronger_reason: string | null
}

/** One remaining business week's share of one rung. Section 11's "evaluate the
 *  remaining weekly promotion events individually, then aggregate" — this is the
 *  individual figure; the rung's totals are the aggregate. */
export interface InterventionWeek {
  week_key: string
  week_number: number
  ordinal: number
  label: string
  /** The promotion EVENTS the week carries, as their own Promotion_Ids. The
   *  non-promoted marker is excluded — it is the absence of a promotion. */
  promotion_ids: string[]
  promoted: boolean
  measured_units: number
  measured_units_display: string
  units: RescueBand
  trade_spend: number | null
  trade_spend_display: string
}

/** What an intervention would actually act on, and how the cadence counts it. */
export interface RemainingScope {
  weeks: {
    week_key: string
    week_number: number
    ordinal: number
    label: string
    promotion_ids: string[]
    promoted: boolean
    measured_units: number
    treatable_products: number
  }[]
  weeks_remaining: number
  /** WEEKLY: one per remaining week. MONTHLY: one treatment across them all. */
  promotion_opportunities: number
  opportunity_label: string
  distinct_promotion_ids: string[]
  treatable_products: number
  carried_products: number
  basis: string
  completed_weeks_untouched: string
}

export interface Intervention {
  level: number
  kind: InterventionKind
  ladder_label: string
  treatment: string | null
  /** Null on the maintain rung: it did not run at a 0% depth, it ran at
   *  whatever the data holds — see `measured_depth_pct`. */
  discount_pct: number | null
  discount_display: string
  measured_depth_pct: number | null
  measured_depth_display: string
  mechanic: string | null
  level_note: string | null
  uplift: { low: number; high: number }
  /** The treatable population only, so the rungs are comparable with each
   *  other. */
  units: RescueBand
  /** Treatable plus carried, so the figure is comparable with the month's own
   *  measured remainder. */
  remaining_units: RescueBand
  projected_month_end: RescueBand
  achievement_pct: { low: number | null; high: number | null }
  /** Decided at the LOW end of the approved band and only there. */
  reaches_target: boolean
  recovery_units: RescueBand
  trade_spend: number | null
  trade_spend_display: string
  additional_trade_spend: number | null
  additional_trade_spend_display: string
  incremental_units: number | null
  incremental_units_display: string
  incremental_sales: number | null
  incremental_sales_display: string
  roi_multiple: number | null
  roi_display: string
  margin_pct: number | null
  margin_display: string
  estimable: boolean
  unavailable_reason: string | null
  within_budget: boolean
  budget_reason: string | null
  by_week: InterventionWeek[]
}

export interface RescueRecommendation {
  action: 'maintain' | 'discount' | 'clearance' | null
  level: number | null
  reason: string
  reaches_target: boolean | null
  ranking_basis: string | null
  candidates_considered: number
  intervention: Intervention | null
}

export interface RescuePopulation {
  treatable_products: number
  treatable_rows: number
  carried_products: number
  carried_units: number
  carried_units_display: string
  carried_reason: string | null
  remaining_products: number
}

export interface RescueProvenance {
  response_rule: string
  promotion_cost_rate: number
  approved_discount_pct: number[]
  clearance_mechanics: {
    treatment: string
    name: string
    discount_pct: number
    uplift_low: number
    uplift_high: number
  }[]
  clearance_basis: string
  economics: string
  kpi_engine: string
  day_grain: string
  selection_scope: string
  option_cascade: string
  cadence_basis: string
  promotion_identity: string
  intervention_scope: string
  days_in_month_basis: string
  decision_rule: string
  ranking_basis: string
  discount_ceiling: string
  cannibalization: string
  run_rate: string
  execution: string
}

export interface RescueMeta {
  mode: string
  currency: string
  base_currency: string
  exchange_rate: number
  max_discount_pct: number
  monthly_checkpoint_week: number
  on_track_attainment_pct: number
  watch_attainment_pct: number
}

export interface TargetRescueScopeRequest {
  month: number
  year?: number | null
  channel?: string[] | null
  category?: string[] | null
  /** Product_id values. Below `category` in the hierarchy — a product from
   *  another category is a 422, not an empty scope. */
  product?: string[] | null
  /** A COMPLETED BUSINESS WEEK — an ordinal, `'auto'`, or `'latest'`. Never a
   *  day: the dataset has no trustworthy daily grain to read one from. */
  checkpoint?: CheckpointValue | null
  currency?: string
}

export interface TargetRescueRequest extends TargetRescueScopeRequest {
  target_units: number
  current_discount_pct: number
  max_additional_trade_spend?: number | null
}

export interface TargetRescueScopeResponse {
  mode: string
  status: RescueStatus
  message: string | null
  scope: RescueScopeBlock
  cadence: CadenceBlock
  checkpoint: CheckpointBlock | null
  options: CascadeOptions
  reference_target: RescueReferenceTarget | null
  measured: RescueMeasured | null
  discount: RescueDiscountBlock
  budget: RescueBudget | null
  ready: boolean
  provenance: RescueProvenance
  meta: RescueMeta
}

export interface TargetRescueResponse {
  mode: string
  status: RescueStatus
  message: string | null
  scope: RescueScopeBlock
  cadence: CadenceBlock
  checkpoint: CheckpointBlock | null
  options: CascadeOptions
  progress: RescueProgress | null
  target_status: RescueTargetStatus | null
  pace: RescuePace | null
  gap: RescueGap | null
  current_treatment: RescueCurrentTreatment | null
  /** Empty for a closed month: there is no remaining period for a treatment to
   *  act on, and four rungs each saying "cannot be estimated" would read as a
   *  failed attempt rather than an inapplicable question. */
  interventions: Intervention[]
  recommendation: RescueRecommendation | null
  evidence: string[]
  remaining_scope: RemainingScope | null
  budget: RescueBudget | null
  population: RescuePopulation | null
  discount: RescueDiscountBlock
  provenance: RescueProvenance
  meta: RescueMeta
}
